dataset_path: Jessemel/pixmocount-test
task: "pixmocount"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.pixmocount_doc_to_visual
doc_to_text: !function utils.pixmocount_doc_to_text
doc_to_target: !function utils.pixmocount_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.pixmocount_process_results
metric_list:
  - metric: pixmocount_accuracy
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with integer and nothing else. For example, if the answer is 1, you should output 1."
metadata:
  version: 0.0 