dataset_path: vikhyatk/CountBenchQA
task: "countbench"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.countbench_doc_to_visual
doc_to_text: !function utils.countbench_doc_to_text
doc_to_target: !function utils.countbench_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.countbench_process_results
metric_list:
  - metric: countbench_accuracy
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question with number only."
metadata:
  version: 0.0